### ISSUE TITLE
CopyQ: Command Merge and Delete ?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/copyq-commands#55]
Hi.
Where is Command: Merge and Delete ?
copyq: 
add(input())
I can not find it anymore.

It should not jump automatically to the top of the tab.

**Comment by hluk** [comment]
> Where is Command: Merge and Delete ?

I don't remember this. Any idea where did this come from?

In script, `add(...)` only adds new item to the top of the list.

**Comment by Clemens-Ratte-Polle** [comment]
dont know anymore, perhaps my own creation? 
What do you think about:
add(input()
?

I test and look around...

Here is your command as answer named from 3 Jun 2019:
Merge and Delete

[Command]
Command="
    copyq:
    add(input())"
Icon=\xf022
InMenu=true
Input=text/plain
Name=Merge and Delete
Remove=true
Shortcut=ctrl+shift+m

https://github.com/hluk/CopyQ/issues/1158#issuecomment-498276994

But it does not exist in the FAQ:
https://copyq.readthedocs.io/en/latest/search.html?q=merge&check_keywords=yes&area=default
Is this a inofficial command?
Where can i find a complete list of official commands?
-

Solution! And perhaps problem too.
I pasted your (inofficial?) command "Merge and Delete" in F6 command list and result is:
add(input())

Is that OK?
What happens?
-

And if i paste this official command to the command list F6:
Join Selected Items

[Command]
Name=Join Selected Items
Command=copyq add -- %1
InMenu=true
Icon=\xf066
Shortcut=Space

https://copyq.readthedocs.io/en/latest/command-examples.html#join-selected-items

the resulting code is:
copyq add -- %1

What happens?
---

**Comment by hluk** [comment]
Any command mentioned in the documentation at https://copyq.readthedocs.io and also in this repo (master branch) should work, otherwise it is a bug.

If you paste [Join Selected Items](https://copyq.readthedocs.io/en/latest/command-examples.html#join-selected-items) the "Command" edit box would contain `copyq add -- %1` - there are other UI elements that should get populated after pasting the code - for example the "Shortcut" would contain "Space" (saving the command and pressing Space after selecting multiple items in the item-list/clipboard-history would create new item with concatenated text from all the selected items).
