### ISSUE TITLE
wayland-support.ini does not work with menu

### ISSUE THREAD

**Issue by abdullah1116** [hluk/copyq-commands#83]
wayland-support.ini does not work with menu 
its working if i select "paste as plain text"

for testing i add serverLog in sendShortcut
it does not log when im selecting but it log when i do "paste as plain text"

i think global.paste does not run when we do direct paste from menu

**Comment by abdullah1116** [comment]
hey, thanks for commit. can you help me please how can i use it

from my understanding, do i have to overwrite something somehow like `ScriptOverrides::Paste` ?? idk.

its not working be default ..

**Comment by hluk** [comment]
@abdullah1116 Did you remove the old command and add new version? The paste is overridden here: https://github.com/hluk/copyq-commands/blob/62b82a5fc01cc961080058f9e7ad1ecd0723f5ad/Scripts/wayland-support.ini#L90-L92

But you need correctly configured [ydotool](https://github.com/ReimuNotMoe/ydotool).

To test if the paste function is triggered, you can modify it so that a popup is shown:

```js
    global.paste = function() {
        popup('PASTE')
        sendShortcut('42:1', '110:1', '110:0', '42:0')
    }
```
