### ISSUE TITLE
SYNC - SETUP & FORCING / INITIAL OPERATION

### ISSUE THREAD

**Issue by qalisto** [hluk/copyq-commands#94]
_Apologies_, but I searched and could not resolve this _query_ -  which is probably an embarrassingly obvious in some way that I missed. 

In both my LNX (MX) and Win11 installations I cannot (for the life of me) get files to **Sync** to either my external cloud OR an internal directory.

I have tried multiple TAB and destination FOLDER variants.  (See Image)
I have tried _Closing_ and _Re-opening_ the App. 

So, how about this ... WHAT is the command (method) of FORCING the Sync operation to occur?  I just want to see one single successful Sync either locally or in a Cloud folder.

I have not found the Sync user info page to be instructive in this regard.  (Sorry - this section is dishearteningly _thin_.)

So ... HOW does a User get a simple, first-time, **Sync** of Items under a _Tab name_?

And then, can someone provide a _Step x Step_, explanation of the precise SYNTAX to specify for TAB NAME and PATH in _Preferences_?  Are there prefix or suffix characters I have neglected to include??

Another thing not clarified in the Support Docs is IF or HOW recursive "Tab" DIRs are or could be included.  OR if all sub-Tabs must be specified as separate entries.  _(If not, would be an obvious Feature Request)_. 

With apologies for being a "Dummy" if I missed something in the Config that is obvious - but I really need to Sync the exact Clips for 2 machines which will read an external cloud drive containing the CPQ target ![CPQ SYNC CFG](https://github.com/hluk/copyq-commands/assets/3213006/63ff3f6e-68db-496a-bc61-62ff518c7368) for Items copied.

Upon success, I would leap for joy.

**Comment by garulovilla** [comment]
Hi @qalisto.

I had seen that synchronization section, but had not experimented with it, it is always good to learn something new 😄.

![image](https://github.com/hluk/copyq-commands/assets/4468146/a9729d86-ba54-41ec-8cde-ebf9b20b9dca)

I put this configuration to see how it worked, and it seems that it is generating the files in the specified directory. I think that to synchronize the "subtabs" it is necessary to place each record.

I had a problem, when changing the tap folder "&Root" (for example, before I had "test_sync/root" and I changed to "test_sync"), but I think it was because I changed it directly (writing it in the cell) and do not select it with the explore icon. But I restarted CopyQ and it started syncing without problems.

I checked all this in Win10, I don't know if it is an operating system issue.

**Comment by qalisto** [comment]
Thank you 

It now seems to be working.  It seems that the "&" **must** be included in the tab path.


> Hi @qalisto.
> 
> I had seen that synchronization section, but had not experimented with it, it is always good to learn something new 😄.
>
