### ISSUE TITLE
CopyQ 8 slow

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [hluk/copyq-commands#96]
hi.
Sometimes CopyQ grows over 80MB with heavy HD usage and slows down the whole computer.
The work with it is also getting hard with very slow actions of merging etc.
This happens after the update to 8.0.0.

**Comment by Clemens-Ratte-Polle** [comment]
deleting and merging element lasts 5 seconds, no productive work possible anymore since update to 8.
CQ HD usage in process manager too high, everything else is waiting.
Often CQ gets greyes out and no feedback message appears... o_O
What happens?

**Comment by Clemens-Ratte-Polle** [comment]
ok, now CQ is so lame that a delete process lasts on and during that a merge command with the element to delete works even so - and the delete action will be forgotten.
???
Perhaps some commands are not optimized

**Comment by hluk** [comment]
Hmm, this is probably because larger items are now stored in separate files and read only when needed. This would normally improve performance and memory consumption but some operations might take long time to finish (e.g. search in some cases or iterating over item data in commands).

You can disable this feature using the following command (from a console or Action dialog - F5 shortcut):

```
copyq config item_data_threshold -1
```

After this you also need to modify tab (e.g. just move or add an item) for this to update the data.

Is this happening on Windows?

**Comment by hluk** [comment]
There are couple of places where CopyQ reads a lot of data unnecessarily. Fix: https://github.com/hluk/CopyQ/pull/2686
